<head>
    <title>Page Title</title>
    <link rel="stylesheet" href="Css/root.css">
    <link rel="stylesheet" href="Css/dashboard.css">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
</head>
<body>
<?php require_once ("View/templates/header.phtml");

foreach ($obj as $key => $value) {
    if($key != "id"){
        echo '<p type="text" style="position: absolute; left: '. $value["position"][0] .'; top: '. $value["position"][1] .';"> ' . $value["content"] . '</p>';
    }
}
?>
</body>