<head>
    <title>Page Title</title>
    <link rel="stylesheet" href="Css/index.css">
</head>
<body>
    <header>
        <img src="Images/redWhiteLogo.png" width="150px" height="auto" class="logo">
    </header>

    <div id="configuration">
        <section class="config slides">
            <p>hujhdgsdff</p>
        </section>

        <section class="config openSlide">
            <div class="slide">
                <embed type="text/php" src="embeded.php" height="432" width="764">
            </div>
        </section>
    </div>

</body>
